name: Reviewdog

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - develop # プルリクエストのマージ対象がmainの場合実施されます。

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: set up jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: run reviewdog
        env:
          CI_PULL_REQUEST: ${{ github.event.pull_request.number }}
          CI_COMMIT: ${{ github.sha }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: ${{ github.event.repository.name }}
          CI_BRANCH: ${{ github.head_ref }}
          REVIEWDOG_GITHUB_API_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          kotlinc -script ./reviewdog/Main.kts
          cat ./result.txt
          cat ./result.txt | reviewdog -name="test" -efm="%f:%l:%c:%t:%m" -reporter=github-pr-review
      - name: Add a custom comment using GitHub CLI
        if: ${{ github.event_name == 'pull_request' }}
        env:
          # GitHub CLI を認証するためにトークンを環境変数にセット
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 複数行のメッセージを変数に格納
          MESSAGE="## :memo: 最終チェックリスト
          
          - [ ] 命名規則は守られています
          - [ ] テストが追加されています

          > [!CAUTION]
          > この処理は危険です。
          
          上記を確認後、マージを許可します。"

          # gh pr comment コマンドでPRにコメントを投稿
          # -b: body (メッセージ内容)
          # $PR_NUMBER は PRの番号
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr comment $PR_NUMBER -b "$MESSAGE"
